---

- block:

  - name: setting file limites
    lineinfile: 
      dest: /etc/security/limits.conf
      line: 'cuckoo   hard  nofile  999999'

  - name: user
    user:
      name: cuckoo
      groups: cuckoo,vboxusers
      append: yes


  - name: setting file limites 2
    lineinfile: 
      dest: /etc/security/limits.conf
      line: 'cuckoo   soft  nofile  999999'

  become: true
  tags:
    - cuckoo_requirements
    

- block:

  - name: Pyenv | install python 2.7.14
    shell: /home/{{ ansible_user }}/.pyenv/bin/pyenv install 2.7.14
    args:
      creates: /home/{{ ansible_user }}/.pyenv/versions/2.7.14

  - name: Pyenv | create virtual env
    shell: /home/{{ ansible_user }}/.pyenv/bin/pyenv virtualenv 2.7.14 dakd-env4
    args:
      creates: /home/{{ ansible_user }}/.pyenv/versions/dakd-env4

  - name: Installs | apt installs
    apt: name={{ item }} state=installed update_cache=true
    with_items:
      - libbz2-dev
    become: true

  - name: pip bz2
    pip:
      name: Bz2file
      state: latest
      virtualenv: /home/{{ ansible_user }}/.pyenv/versions/dakd-env4

  - name: installing setuptools in virtualenv
    pip: 
      name: setuptools
      virtualenv: /home/{{ ansible_user }}/.pyenv/versions/dakd-env4

  - name: installing cuckoo in virtualenv
    pip: 
      name: cuckoo
      virtualenv: /home/{{ ansible_user }}/.pyenv/versions/dakd-env4
      #extra_args: -i https://pypi.python.org/simple

  become: false
  tags:
   - cuckoo_install