---

- block:


  - name: Installs | apt installs
    apt: name={{ item }} state=installed update_cache=true
    with_items:
      - python
      - python-dev
      - python-pip
      - python-crypto
      - libffi-dev
      - python-virtualenv 
      - python-setuptools
      - libjpeg-dev 
      - zlib1g-dev 
      - swig
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - unzip
      - mongodb
      - postgresql
      - libpq-dev
      - tcpdump
      - apparmor-utils
      - libcap2-bin
    register: cuckoo_requirements


  - name: tcpdump config
    shell: setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump


  become: true
  tags:
    - cuckoo_requirements