---

- block:


  - name: Installs | apt installs
    apt: name={{ item }} state=installed update_cache=true
    with_items:
      - git
      - python-dev
      - python-pip
      - python-crypto
      - vim
      - make
      - build-essential
      - bzip2
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - unzip
      # - llvm
      # - libncurses5-dev
      # - libncursesw5-dev
      # - xz-utils
    register: aptgetinstall01


- block:

  - name: Pyenv | git clone
    git:
      repo: "https://github.com/yyuu/pyenv.git"
      dest: "/home/{{ ansible_user }}/.pyenv"
      #recursive: yes
      force: no
      update: no
      version: HEAD
      accept_hostkey: yes
      #track_submodules: yes
    register: pyenvclone

  - name: Pyenv-virtualenv | git clone
    git:
      repo: "https://github.com/yyuu/pyenv-virtualenv.git"
      dest: "/home/{{ ansible_user }}/.pyenv/plugins/pyenv-virtualenv"
      #recursive: yes
      force: no
      update: no
      version: HEAD
      accept_hostkey: yes
      #track_submodules: yes
    register: pyenv_virtualenv_clone

  - name: Pyenv and  Pyenv-virtualenv| modify .profile
    lineinfile: state=present dest=/home/{{ ansible_user }}/.profile line="{{ item }}"
    with_items:
      - export PYENV_ROOT="$HOME/.pyenv"
      - export PATH="$PYENV_ROOT/bin:$PATH"
      - eval "$(pyenv init -)"
      - source ~/.pyenv/completions/pyenv.bash
      - eval "$(pyenv virtualenv-init -)"

  - name: Pyenv folder permissions
    file: path=/home/{{ ansible_user }}/.pyenv state=directory mode=0755 owner={{ ansible_user }} group={{ ansible_user }} recurse=yes
    become: true
    become_method: sudo
    become_user: root

  - name: Pyenv | install python 2.7.13
    shell: /home/{{ ansible_user }}/.pyenv/bin/pyenv install 2.7.13
    args:
      creates: /home/{{ ansible_user }}/.pyenv/versions/2.7.13
    #when: pyenvclone|succeeded and pyenv-virtualen-clone|succeeded
    register: install_python_2_7_13
    ignore_errors: false


  - name: Pyenv | install python 3.6.3
    shell: /home/{{ ansible_user }}/.pyenv/bin/pyenv install 3.6.3
    args:
      creates: /home/{{ ansible_user }}/.pyenv/versions/3.6.3
    #when: pyenvclone|succeeded and pyenv-virtualen-clone|succeeded
    register: install_python_3_6_3
    ignore_errors: false



  become: false
  tags:
    - pyenvconfig
    - git
    - basic